Add flat delivery price to purchases
rails-up/zakupki pull request #84
Opened 2016-08-31 14:58 UTC by Fatpaher

СПРИНТ 1. Стоимость доставки
Rework purchase_new_spec create purchase with using js

2016-08-31 15:28 UTC, badimalex commented on app/assets/javascripts/new_purchase.coffee
> +      if text == 'фиксированная стоимость'
может есть смысл этот js во вью вынести и сравнить со значением из i18, чтобы не хардкодить?

2016-08-31 15:29 UTC, badimalex commented on spec/features/purchase_new_spec.rb
> +                                  value: 'фиксированная стоимость'
может лучше i18 здесь юзать?)

2016-09-01 08:46 UTC, Fatpaher commented on app/assets/javascripts/new_purchase.coffee
> +      if text == 'фиксированная стоимость'
@badimalex и я с тобой не могу не солгаситься, но есть одно, это значение находится в БД.
То есть надо либо мультилингвовую базу данных делать, либо думать что-то другое. Пока только так.

2016-09-14 10:26 UTC, badimalex commented on app/assets/javascripts/new_purchase.coffee
> +      if text == 'фиксированная стоимость'
я тут подумал, может добавить метод в модель который будет искать(where title ="фиксированная стоимость") и возвращать id записи "фиксированная стоимость"
тогда можно будет избавиться от хардкода везде? а просто обращаться к 
DeliveryPaymentType.fixCostId
как считаешь?

2016-09-14 17:30 UTC, Fatpaher commented on app/assets/javascripts/new_purchase.coffee
> +      if text == 'фиксированная стоимость'
Слушай, а это хорошая идея, так пожалуй и сделаю в ближайшее время

2016-09-17 14:53 UTC, badimalex commented
// @Fatpaher 
я переключился на твою ветку, удалось решить проблему так,
вместо page.execute_script
делай page.evaluate_script
ну и скрипт лучше сохрани где то выше, типа

```ruby
script = <<-SCRIPT
      $('#purchase_end_date').
        pickadate('picker').
        set('select', '#{date}')
    SCRIPT
page.evaluate_script(script)
```
ну и лучше сделай сквош комитов и потом force push когда поправишь проблему.

2016-09-17 17:24 UTC, badimalex requested changes

2016-09-17 17:24 UTC, badimalex commented on spec/features/purchase_new_spec.rb
> +  given(:delivery_payment_cost_types) { create_list(:delivery_payment_cost_type, 2) }
//cc @Fatpaher 
Может зря ты удалил восклицательные знаки, теперь вручную нужно иницилизировать создание данных в бд, для каждого теста. А здесь их всего два и в обеих эти данные нужны были. Как считаешь?

2016-09-17 18:12 UTC, Fatpaher commented on spec/features/purchase_new_spec.rb
> +  given(:delivery_payment_cost_types) { create_list(:delivery_payment_cost_type, 2) }
@badimalex Посмотри внимательно там эти записи создаются для 6 тестов, а нужны только в двух.

2016-09-17 18:28 UTC, badimalex commented on spec/features/purchase_new_spec.rb
> +  given(:delivery_payment_cost_types) { create_list(:delivery_payment_cost_type, 2) }
@Fatpaher  да ты прав, тогда ок)

2019-02-08 20:29 UTC, closed without merging